[package]
name = "main"
version = "0.6.0"
publish.workspace = true
edition.workspace = true

[[bin]]
name = "omnihub"
path = "src/main.rs"

[dependencies]
gpui = { workspace = true }
gpui-component = { workspace = true }
gpui-component-assets = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
semver = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
rust-i18n = { workspace = true }
base64 = { workspace = true }
dirs = {workspace = true}
sys-locale = "0.3"
futures = { workspace = true }
smol = { workspace = true }
db_view = { workspace = true }
terminal = { workspace = true }
terminal_view = { workspace = true }
sftp_view = { workspace = true }
redis_view = { workspace = true }
mongodb_view = { workspace = true }
port_forwarding = { workspace = true }
port_forwarding_view = { workspace = true }
remote_desktop = { workspace = true }
remote_desktop_view = { workspace = true }
remote_file_editor = { workspace = true, features = ["ui"] }
one-core.workspace = true
one-ui.workspace = true
reqwest_client.workspace = true
db.workspace = true
global-hotkey.workspace = true
sha2 = { workspace = true }
flate2 = "1"
tar = "0.4"
sysinfo = "0.32"
raw-window-handle = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
zip = { version = "2", default-features = false, features = ["deflate"] }
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }

[target.'cfg(target_os = "windows")'.build-dependencies]
winresource = "0.1"

[lints]
workspace = true

[dev-dependencies]
tempfile = "3"
