[package]
name = "ssh"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
# Async runtime
tokio = { workspace = true, features = ["fs", "net", "io-util"] }
async-trait = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
rust-i18n = { workspace = true }
dirs = { workspace = true }
uuid = { workspace = true }
# SSH and SFTP
russh.workspace = true
# Proxy support
tokio-socks.workspace = true
# known_hosts 处理
data-encoding = "2.3"
hmac = "0.12"
sha1 = "0.10"

[lints]
workspace = true
