-- SSH 私钥字段从 key_path 迁移到 ssh_private_key
--
-- 重要说明：
-- 同步服务器存储的是加密后的凭证数据（通过 encrypt_json_passwords 加密），
-- 因此无法在 SQL 层直接修改字段名称。
--
-- 迁移将在客户端完成：
-- 1. 客户端运行 20260510000001_ssh_key_content.sql 迁移脚本
-- 2. 客户端读取 key_path 对应的文件内容
-- 3. 将文件内容存储到 ssh_private_key 字段
-- 4. 同步时，sync_data 表中的加密数据会更新
--
-- 这个迁移脚本仅用于文档记录，无需在同步服务器执行。
